FROM node:14-alpine as build

WORKDIR /app

COPY package*.json /app

RUN npm install --production --silent

COPY . /app


FROM node:14-alpine

WORKDIR /app

COPY --from=build /app /app

EXPOSE $API_PORT

CMD npm start
